
USE EMPLOYEE_TRACKER;

INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ("MANAGEMENT");
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ("INTERN");
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ("ENGINEER");
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ("JANITOR");

INSERT INTO ROLE (ROLE_TITLE, ROLE_SALARY, DEPARTMENT_ID) VALUES ("MANAGER", 150000, 1);
INSERT INTO ROLE (ROLE_TITLE, ROLE_SALARY, DEPARTMENT_ID) VALUES ("JUNIOR DEVELOPER", 70000, 3);
INSERT INTO ROLE (ROLE_TITLE, ROLE_SALARY, DEPARTMENT_ID) VALUES ("JANITOR", 8000, 4);
INSERT INTO ROLE (ROLE_TITLE, ROLE_SALARY, DEPARTMENT_ID) VALUES ("INTERN", 30000, 2);


INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID) VALUES ("Miguelangel", "Weill", 1, 1);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID) VALUES("Alexander", "De Asostoa", 3, NULL);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID) VALUES ("Marcos", "Patrocino", 3, NULL);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID) VALUES ("Caitlin", "White", 4, NULL);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID) VALUES ("Chaval", "Chino", 2, NULL);